// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_API_KEY_ANDROID"]!,
    appId: dotenv.env["FIREBASE_APP_ID_ANDROID"]!,
    messagingSenderId: dotenv.env["FIREBASE_MESSAGING_SENDER_ID"]!,
    projectId: dotenv.env["FIREBASE_PROJECT_ID"]!,
    storageBucket: dotenv.env["FIREBASE_STORAGE_BUCKET"]!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_API_KEY_IOS"]!,
    appId: dotenv.env["FIREBASE_APP_ID_IOS"]!,
    messagingSenderId: dotenv.env["FIREBASE_MESSAGING_SENDER_ID"]!,
    projectId: dotenv.env["FIREBASE_PROJECT_ID"]!,
    storageBucket: dotenv.env["FIREBASE_STORAGE_BUCKET"]!,
    iosBundleId: dotenv.env["FIREBASE_IOS_BUNDLE_ID"]!,
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyD-yp0CPjFg2yfg7QJ34Tragihen4gckZM',
  //   appId: '1:560140614397:android:b7c14344c8858cf2d05c94',
  //   messagingSenderId: '560140614397',
  //   projectId: 'oneday-37b90',
  //   storageBucket: 'oneday-37b90.firebasestorage.app',
  // );
  //
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDaLuauKLmEO8X2oWKIe-FrwntuqCsTi60',
  //   appId: '1:560140614397:ios:4f42efd92c794f59d05c94',
  //   messagingSenderId: '560140614397',
  //   projectId: 'oneday-37b90',
  //   storageBucket: 'oneday-37b90.firebasestorage.app',
  //   iosBundleId: 'christian.range.fitnessapp.fitnessApp11',
  // );
}
